### ISSUE TITLE
fed_cifar10 sample does not download the dataset correctly

### ISSUE THREAD

**Issue by reckyless** [FedML-AI/FedML#1590]
I'm running this [example](python/examples/federate/cross_silo/mqtt_s3_fedavg_cifar10_lr_example).I use one Jetson device as the server side and the other as the client side.This is my config.yaml source  file.    
```
common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  using_mlops: false
  random_seed: 0
  config_version: release

environment_args:
  bootstrap: config/bootstrap.sh

data_args:
  dataset: "cifar10"
  data_cache_dir: "~/fedcv_data/"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "mobilenet_v3"
  image_size:
  input_size: 3
  class_num: 10
  model_file_cache_folder: "./model_file_cache" # will be filled by the server automatically
  global_model_file_path: "./model_file_cache/global_model.pt"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 10
  epochs: 1
  batch_size: 4
  client_optimizer: sgd
  lr: 0.01
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 2
  using_gpu: true
#  gpu_mapping_file: config/gpu_mapping.yaml
#  gpu_mapping_key: mapping_default

comm_args:
  backend: "MQTT_S3"
  mqtt_config_path: config/mqtt_config.yaml
  s3_config_path: config/s3_config.yaml

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_image_classification
```

<img width="917" alt="屏幕截图 2023-11-07 171812" src="https://github.com/FedML-AI/FedML/assets/115770276/b92c584b-5dc8-4699-b461-6137cb8c4f7b">
But when I change the [download=False](https://github.com/FedML-AI/FedML/blob/3e6a399e86ca808d065dc918b532e7173b918e91/python/fedml/data/cifar10/without_reload.py#L19) and [self.download = download](https://github.com/FedML-AI/FedML/blob/3e6a399e86ca808d065dc918b532e7173b918e91/python/fedml/data/cifar10/without_reload.py#L26C9-L26C33) in this file to `download=True`, the dataset is downloaded and run.

- My environment is as follows
![微信图片_20231107173559](https://github.com/FedML-AI/FedML/assets/115770276/5f358497-37a7-4e75-93da-470078e3aaa3)

- My device is agx jetson xavier.The docker container version used is nvidia-jetson-l4t-ml-r35.1.0-py3.
